/**
 * 100 Creative, Witty, and Fierce Hangman & Word-Themed Team Names
 */
export const TEAM_NAMES = [
  "The Vowel Owls",
  "Consonant Crushers",
  "Lexicon Legends",
  "The Dangling Participles",
  "Word Nerds",
  "Syntax Strikers",
  "Oxford Comma Commandos",
  "The Rogue Rhymers",
  "Syllable Snipers",
  "Gallows Gurus",
  "Anagram Assassins",
  "The Spelling Bees",
  "Alphabet Mavericks",
  "Noose Negotiators",
  "The Cryptic Crosswords",
  "Thesaurus Rex",
  "Vocab Vandals",
  "Pun Intended",
  "Letter Legion",
  "Scrabble Scoundrels",
  "The Grammar Police",
  "Silent Letter Syndicate",
  "The Hanging Chads",
  "Quizzical Questers",
  "Suffix Savages",
  "Prefix Pirates",
  "The Last Straws",
  "Hangman Hitmen",
  "Riddle Raiders",
  "The Jargon Juggernauts",
  "Etymology Elite",
  "The Rope Walkers",
  "Semantic Samurai",
  "The Hyphenated Heroes",
  "Wordle Warlords",
  "The Bare Minimum",
  "Vowel Movement",
  "Phonic Phantoms",
  "The Apostrophe Army",
  "Glyph Gladiators",
  "Dialect Destroyers",
  "The Run-On Sentences",
  "Boggle Bandits",
  "Linguistic Luminaries",
  "The Wordplay Wizards",
  "Clue Chasers",
  "The Terminal Letters",
  "Idiom Icons",
  "The Quick Brown Foxes",
  "Blunder Guessers",
  "Morpheme Monsters",
  "The Dead Poets",
  "Capital Offenders",
  "The Acronym Aces",
  "Blank Space Bandits",
  "The Gallows Gang",
  "Dictionary Detectives",
  "The Tense Shifts",
  "Tongue Twisters",
  "The Alliteration Alliance",
  "Decipher Dynamos",
  "The Semicolon Squad",
  "Prose Pros",
  "The Blind Guessers",
  "Limb Savers",
  "The Runic Rebels",
  "Syntax Errors",
  "The Red Herrings",
  "Metaphor Marauders",
  "Cipher Syndicate",
  "The Stutter Steps",
  "Punny Business",
  "The Missing Links",
  "Verb Velocity",
  "The Trailing Commas",
  "Rhyme Time Rogues",
  "The Final Vowels",
  "Clueless Champions",
  "Gallows Humor",
  "The Irony Icons",
  "Spelling Specters",
  "The Root Words",
  "Onomatopoeia Ops",
  "The Word Smiths",
  "Lucky Guesses",
  "The Stray Consonants",
  "Shuffled Letters",
  "The Wildcards",
  "Hanging By A Thread",
  "The Bold Typers",
  "Underline Underground",
  "The Crypt Keepers",
  "Letter Lockers",
  "The Spellbinders",
  "Brain Teasers",
  "The Last Guessers",
  "High Stakes Spellers",
  "The Scrabble Kings",
  "Vocab Vectors",
  "The Final Word"
];

export default TEAM_NAMES;
